In [190]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)

In [191]:
df = pd.read_csv('C:\\Users\\user\\Mahesh Anand ML\\Migraine.csv',index_col=0)

In [192]:
df.head()

id  time  dos hatype  age  airq  medication headache  Gender
1   1   -11  753   Aura   30   9.0  continuing      yes  female
2   1   -10  754   Aura   30   7.0  continuing      yes  female
3   1    -9  755   Aura   30  10.0  continuing      yes  female
4   1    -8  756   Aura   30  13.0  continuing      yes  female
5   1    -7  757   Aura   30  18.0  continuing      yes  female

#### CHECKING IF HEADACHE HAS AN EFFECT ON HEADACHE TYPE

In [193]:
ha = pd.crosstab(df['hatype'],df['headache'])
ha

headache   no   yes
hatype             
Aura      581  1129
Mixed      96   361
No Aura   809  1176

In [194]:
from scipy.stats import chi2_contingency

In [195]:
chi2_contingency(ha)

(67.20681271927494,
 2.5481561909783057e-15,
 2,
 array([[ 612.00867052, 1097.99132948],
        [ 163.56021195,  293.43978805],
        [ 710.43111753, 1274.56888247]]))

###### We reject the null hypothesis.

#### CHECKING IF AGE HAS AN EFFECT ON HEADACHE TYPE

In [196]:
aa = df[df['hatype']=='Aura']['age']
am = df[df['hatype']=='Mixed']['age']
an = df[df['hatype']=='No Aura']['age']

In [197]:
from scipy.stats import f_oneway

In [198]:
f_oneway(aa,am,an)

F_onewayResult(statistic=53.863659978037205, pvalue=8.050903622534975e-24)

###### We reject the null hypothesis that mean of AGE of all the three types of headache are same since p-value < 0.05.

#### CHECKING IF GENDER HAS AN EFFECT ON HEADACHE TYPE

In [199]:
gen = pd.crosstab(df['hatype'],df['Gender'])
gen

Gender   female  male
hatype               
Aura       1593   117
Mixed       291   166
No Aura    1661   324

In [200]:
from scipy.stats import chi2_contingency

In [201]:
chi2_contingency(gen)

(259.94962922327386,
 3.569893234435195e-57,
 2,
 array([[1460.00722543,  249.99277457],
        [ 390.18906551,   66.81093449],
        [1694.80370906,  290.19629094]]))

###### We reject the null hypothesis that proportion of male having all the three types of headache are same as the proportion of females having all the three types of headache since p-value < 0.05

#### CHECKING IF AIRQ HAS AN EFFECT ON HEADACHE TYPE

In [202]:
aa1 = df[df['hatype']=='Aura']['airq']
am2 = df[df['hatype']=='Mixed']['airq']
an3 = df[df['hatype']=='No Aura']['airq']

In [203]:
f_oneway(aa1,am2,an3)

F_onewayResult(statistic=30.90848974976332, pvalue=4.738384871920145e-14)

###### We reject the null hypothesis that mean of AIRQ of all the three types of headache are same since p-value < 0.05.

#### CHECKING IF DOS HAS AN EFFECT ON HEADACHE TYPE

In [204]:
da = df[df['hatype']=='Aura']['dos']
dm = df[df['hatype']=='Mixed']['dos']
dn = df[df['hatype']=='No Aura']['dos']

In [205]:
f_oneway(da,dm,dn)

F_onewayResult(statistic=333.29106869785664, pvalue=5.87125110646331e-135)

###### We reject the null hypothesis that mean of DOSAGE of all the three types of headache are same since p-value < 0.05

In [206]:
da.mean()

551.412865497076

In [207]:
dn.mean()

653.2826196473552

In [208]:
dm.mean()

974.706783369803

In [209]:
an.mean()

44.20503778337532

#### CHECKING IF TIME HAS AN EFFECT ON HEADACHE TYPE

In [210]:
ta = df[df['hatype']=='Aura']['time']
tm = df[df['hatype']=='Mixed']['time']
tn = df[df['hatype']=='No Aura']['time']

In [211]:
f_oneway(ta,tn,tm)

F_onewayResult(statistic=53.33800295628198, pvalue=1.3439545928461342e-23)

###### We reject the null hypothesis that mean of TIME of all the three types of headache are same since p-value < 0.05

#### CHECKING IF MEDICATION HAS AN EFFECT ON HEADACHE TYPE

In [212]:
m = pd.crosstab(df['hatype'],df['medication'])
m

medication  continuing  none  reduced
hatype                               
Aura              1079   354      277
Mixed              194   113      150
No Aura           1113   318      554

In [213]:
chi2_contingency(m)

(119.59177947992337,
 6.529039020102319e-25,
 4,
 array([[ 982.6734104 ,  323.30202312,  404.02456647],
        [ 262.62090559,   86.40293834,  107.97615607],
        [1140.70568401,  375.29503854,  468.99927746]]))

###### We reject the null hypothesis that proportion of people getting CONTINUING MEDICATION = proportion of people getting NO MEDICATION = proportion of people getting REDUCED MEDICATION are same since p-value < 0.05

In [214]:
x = df.drop(['id','hatype'],axis=1)
y = df['hatype']

In [215]:
x.columns

Index(['time', 'dos', 'age', 'airq', 'medication', 'headache', 'Gender'], dtype='object')

#### ONE HOT ENCODING

In [216]:
x_headache = pd.get_dummies(x['headache'])
x_medication = pd.get_dummies(x['medication'])
x_gender = pd.get_dummies(x['Gender'])

In [217]:
x_update = pd.concat([x,x_headache,x_medication,x_gender],axis=1)

In [218]:
x_update.head()

time  dos  age  airq  medication headache  Gender  no  yes  continuing  \
1   -11  753   30   9.0  continuing      yes  female   0    1           1   
2   -10  754   30   7.0  continuing      yes  female   0    1           1   
3    -9  755   30  10.0  continuing      yes  female   0    1           1   
4    -8  756   30  13.0  continuing      yes  female   0    1           1   
5    -7  757   30  18.0  continuing      yes  female   0    1           1   

   none  reduced  female  male  
1     0        0       1     0  
2     0        0       1     0  
3     0        0       1     0  
4     0        0       1     0  
5     0        0       1     0

In [219]:
x_final = x_update.drop(['headache','medication','Gender'],axis=1)
x_final.head()

time  dos  age  airq  no  yes  continuing  none  reduced  female  male
1   -11  753   30   9.0   0    1           1     0        0       1     0
2   -10  754   30   7.0   0    1           1     0        0       1     0
3    -9  755   30  10.0   0    1           1     0        0       1     0
4    -8  756   30  13.0   0    1           1     0        0       1     0
5    -7  757   30  18.0   0    1           1     0        0       1     0

In [220]:
x_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4152 entries, 1 to 4152
Data columns (total 11 columns):
time          4152 non-null int64
dos           4152 non-null int64
age           4152 non-null int64
airq          4152 non-null float64
no            4152 non-null uint8
yes           4152 non-null uint8
continuing    4152 non-null uint8
none          4152 non-null uint8
reduced       4152 non-null uint8
female        4152 non-null uint8
male          4152 non-null uint8
dtypes: float64(1), int64(3), uint8(7)
memory usage: 190.6 KB


### LOGISTIC REGRESSION

In [221]:
from sklearn.linear_model import LogisticRegression

In [229]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_final,y,test_size = 0.3 ,random_state = 0)

In [230]:
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [224]:
from sklearn import metrics

In [225]:
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy*100

51.20385232744783

In [226]:
cm = metrics.confusion_matrix(y_test,y_pred)
cm

array([[189,  19, 301],
       [ 18,  46,  76],
       [176,  18, 403]], dtype=int64)

In [227]:
from sklearn.model_selection import KFold
from sklearn import metrics
kf=KFold(n_splits=5,shuffle=True,random_state=0)
for model,name in zip([model],['Logistic Regression']):
    acc=[]
    for train_idx,test_idx in kf.split(x_final,y):
        xtrain,xtest=x_final.iloc[train_idx,:],x_final.iloc[test_idx,:]
        ytrain,ytest=y.iloc[train_idx],y.iloc[test_idx]
        model.fit(xtrain,ytrain)
        y_pred=model.predict(xtest)
        acc.append(metrics.accuracy_score(ytest,y_pred))
    print('Accuracy scores: %0.03f (+/- %0.5f)[%s]' % (np.mean(acc),np.var(acc,ddof=1),name))

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regre

Accuracy scores: 0.534 (+/- 0.00079)[Logistic Regression]


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [231]:
cr = metrics.classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

        Aura       0.49      0.37      0.42       509
       Mixed       0.55      0.33      0.41       140
     No Aura       0.52      0.68      0.59       597

    accuracy                           0.51      1246
   macro avg       0.52      0.46      0.47      1246
weighted avg       0.51      0.51      0.50      1246

